apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJkbWxyZEc5eVkyaDFhMmhoYm5SelpYWTZaMmh3WHpaME4yZEhVMGRKWlcxcVVqaHBlamhQVFZkcVdsTXpVMDlWVUc1MVZqTlVWMFpPVWc9PSIKCQl9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIsCgkicGx1Z2lucyI6IHsKCQkiLXgtY2xpLWhpbnRzIjogewoJCQkiZW5hYmxlZCI6ICJmYWxzZSIKCQl9Cgl9Cn0K
type: kubernetes.io/dockerconfigjson
